#define _QUOTE(A)     #A
#define _MAKESTR(A)   _QUOTE(A)

#define PRF_HINIFILE        "NFM.INI"
#define PRF_APPL            "NFM"
#define PRF_FRAME_POS       "FramePos"
#define PRF_BTN_POS         "BtnPos"
#define PRF_TREE_FONT       "TreeFont"
#define PRF_TREE_COLORFORE  "TreeColorFore"
#define PRF_TREE_COLORBACK  "TreeColorBack"
#define PRF_FILE_FONT       "FileFont"
#define PRF_FILE_COLORFORE  "FileColorFore"
#define PRF_FILE_COLORBACK  "FileColorBack"
#define PRF_PREV_FONT       "PrevFont"
#define PRF_PREV_COLORFORE  "PrevColorFore"
#define PRF_PREV_COLORBACK  "PrevColorBack"
#define PRF_POSSEPX         "PosSepX"
#define PRF_POSSEPY         "PosSepY"
#define PRF_FLAGSEPY        "FlagSepY"
#define PRF_TIPOPREVIEW     "TypePreview"
#define PRF_GRAP_POS        "GraphPos"
#define PRF_DEF_VIEW        "DefaultView"
#define PRF_FILE_MASK       "FileMask"

/* Control low level */
#define ID_FRAME                    100
#define ID_BARRA_SEPX               101
#define ID_BARRA_SEPY               102
#define ID_TREE_TOP                 103
#define ID_FILES_TOP                104
#define ID_CONT_TREE                105
#define ID_CONT_FILES               106
#define ID_ICON                     107
#define ID_LIST                     108
#define ID_CONTENT                  109
#define ID_DETAIL                   110
#define ID_EXIT                     111
#define ID_PARENT                   112
#define ID_RELOAD                   113
#define ID_PREVIEW                  114
#define ID_PREVIEW_BMP              115
#define ID_TIPO_PREVIEW             116
#define ID_OPTIONS                  117
#define ID_PREVIEW_TXT              118
#define ID_SEL_ALL                  119
#define ID_SEL_INVERT               120
#define ID_TREE_BOTTOM              121
#define ID_FILES_BOTTOM             122
#define ID_VAIA                     123
#define ID_SW_BARRA_MENU            124
#define ID_SW_BARRA_STATO           125
#define ID_COMBO_DRIVE              126
#define ID_MN_APRI                  127
#define ID_MN_MODIFICARE            128
#define ID_MN_IMPOSTAZIONI          129
#define ID_MN_APRIICONE             130
#define ID_MN_APRITREE              131
#define ID_MN_APRIDETT              132
#define ID_MN_SPOSTARE              133
#define ID_MN_COPIARE               134
#define ID_MN_COPIACOLLEGATA        135
#define ID_MN_CANCELLARE            136
#define ID_MN_RINOMINARE            137
#define ID_MN_FORMATTARE            138
#define ID_MN_CONTROLLARE           139
#define ID_MN_PARTIZIONARE          140
#define ID_MN_VISGRAFICA            141
#define ID_MN_NEWFOLD               142
#define ID_MN_NEWCOLL               143
#define ID_MN_ANNULLA               144
#define ID_MN_TAGLIA                145
#define ID_MN_COPIA                 146
#define ID_MN_INCOLLA               147

/* Dialog top level */
#define ID_BARRA_MENU               200

#define ID_BARRA_STATO              300

#define ID_VAIA_DIAG                400
#define ID_VAIA_EF                  401
#define ID_VAIA_OK                  402
#define ID_VAIA_CANCEL              403

#define ID_OPER                     500
#define ID_OPER_MSG                 501

/* Bitmap */
#define ID_BMP_PADRE               1001
#define ID_BMP_GRAFICO             1002
#define ID_BMP_PREVIEW             1003
#define ID_BMP_PTHUMB              1004
#define ID_BMP_PNORM               1005
#define ID_BMP_PSTRETCH            1006
#define ID_BMP_IMPOSTAZ            1007
#define ID_BMP_AGGIORNA            1008
#define ID_BMP_CANCELL             1009
#define ID_BMP_CREA                1010
#define ID_BMP_ICON                1011
#define ID_BMP_LIST                1012
#define ID_BMP_CONTENT             1013
#define ID_BMP_DETAIL              1014
#define ID_BMP_SU                  1015
#define ID_BMP_GIU                 1016

/* Icone */
#define ID_ICON_DESKTOP            2000
#define ID_ICON_DISKA              2001
#define ID_ICON_CDROM              2002
#define ID_ICON_DISK               2003
#define ID_ICON_LANDISK            2004
#define ID_ICON_FOLDERO            2005

/* Menu top level */
#define ID_MN_CONTTREES            3000
#define ID_MN_CONTFILES            3001
#define ID_MN_CONTDRIVES           3002
